wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1743302914.390121
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.7
      5: 0.14.0
      8:
      - 5
apply_dropout:
  desc: null
  value: false
apply_masking:
  desc: null
  value: false
apply_pruning:
  desc: null
  value: true
aug_type:
  desc: null
  value: color_crop_cutout
augment:
  desc: null
  value: false
batch_real:
  desc: null
  value: 64
batch_size:
  desc: null
  value: 64
batch_syn_max:
  desc: null
  value: 128
beta:
  desc: null
  value: 1.0
bias:
  desc: null
  value: false
bottleneck:
  desc: null
  value: true
capacity_thres:
  desc: null
  value: 0
data_dir:
  desc: null
  value: /mnt/16THDD/Fred/FredH/CILAB/data
dataset:
  desc: null
  value: cifar10
datatag:
  desc: null
  value: cifar10
decode_type:
  desc: null
  value: single
depth:
  desc: null
  value: 3
dist:
  desc: null
  value: null
distributed_num:
  desc: null
  value: null
dropout_rate:
  desc: null
  value: 0.1
dsa:
  desc: null
  value: true
dsa_strategy:
  desc: null
  value: color_crop_flip_scale_rotate
dseed:
  desc: null
  value: 0
early:
  desc: null
  value: 0
epoch_print_freq:
  desc: null
  value: 1000
epochs:
  desc: null
  value: 1000
f_idx:
  desc: null
  value: '2'
factor:
  desc: null
  value: 2
fc:
  desc: null
  value: false
fix_iter:
  desc: null
  value: -1
grad_simi:
  desc: null
  value: false
imagenet_dir:
  desc: null
  value: ../data/imagenet/
init:
  desc: null
  value: mix
inner_loop:
  desc: null
  value: 100
inner_schedule:
  desc: null
  value: false
ipc:
  desc: null
  value: 1
load_memory:
  desc: null
  value: true
lr:
  desc: null
  value: 0.01
lr_img:
  desc: null
  value: 0.0005
masking_type:
  desc: null
  value: null
match:
  desc: null
  value: grad
metric:
  desc: null
  value: mse
mix_p:
  desc: null
  value: 0.5
mixup:
  desc: null
  value: cut
mixup_net:
  desc: null
  value: cut
modeltag:
  desc: null
  value: conv3in
mom_img:
  desc: null
  value: 0.5
momentum:
  desc: null
  value: 0.9
n_data:
  desc: null
  value: 2000
name:
  desc: null
  value: ''
nch:
  desc: null
  value: 3
nclass:
  desc: null
  value: 10
nclass_sub:
  desc: null
  value: -1
net_epoch:
  desc: null
  value: 1
net_type:
  desc: null
  value: convnet
niter:
  desc: null
  value: 2000
norm_type:
  desc: null
  value: instance
num_tune_subnetwork:
  desc: null
  value: 0
phase:
  desc: null
  value: -1
pool_number:
  desc: null
  value: 5
pretrained:
  desc: null
  value: false
pretrained_dir:
  desc: null
  value: ./pretrained/cifar10/conv3in_cut_dsa_p
print_freq:
  desc: null
  value: 10
pruning_ratio:
  desc: null
  value: 0.8
pruning_ratio_deep:
  desc: null
  value: null
pruning_ratio_shallow:
  desc: null
  value: null
pruning_ratio_type:
  desc: null
  value: uniform
pruning_type:
  desc: null
  value: global
pt_from:
  desc: null
  value: -1
pt_num:
  desc: null
  value: 1
repeat:
  desc: null
  value: 1
reproduce:
  desc: null
  value: false
rrc:
  desc: null
  value: true
saliency:
  desc: null
  value: false
same_compute:
  desc: null
  value: false
sample_accrange:
  desc: null
  value:
  - 70
  - 80
save_ckpt:
  desc: null
  value: false
save_dir:
  desc: null
  value: './results/cifar10/conv3in_grad_mse_nd2000_cut_niter2000_factor2_lr0.0005_mom_img0.5_mix_ipc:1_sample_accrange:(70-80)_poolNumber:
    5_pruning(0.8)_pruning_type:global_tuneEpoch:0_pretrained:conv3in_cut_dsa_p'
seed:
  desc: null
  value: 0
size:
  desc: null
  value: 32
slct_type:
  desc: null
  value: idc
smoothing:
  desc: null
  value: 0
strategy:
  desc: null
  value: null
syn_soft_label:
  desc: null
  value: false
t_depth:
  desc: null
  value: 50
t_net_type:
  desc: null
  value: resnet
t_norm_type:
  desc: null
  value: batch
tag:
  desc: null
  value: '_grad_mse_nd2000_cut_niter2000_factor2_lr0.0005_mom_img0.5_mix_ipc:1_sample_accrange:(70-80)_poolNumber:
    5_pruning(0.8)_pruning_type:global_tuneEpoch:0_pretrained:conv3in_cut_dsa_p'
teacher_soft_label:
  desc: null
  value: false
temperature:
  desc: null
  value: null
test:
  desc: null
  value: false
time:
  desc: null
  value: false
track_training:
  desc: null
  value: false
verbose:
  desc: null
  value: false
wd_img:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0005
width:
  desc: null
  value: 1.0
workers:
  desc: null
  value: 8
