wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1743308514.135168
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.7
      5: 0.14.0
      8:
      - 5
apply_pruning:
  desc: null
  value: true
aug_type:
  desc: null
  value: color_crop_cutout
augment:
  desc: null
  value: true
batch_real:
  desc: null
  value: 128
batch_size:
  desc: null
  value: 128
batch_syn_max:
  desc: null
  value: 128
beta:
  desc: null
  value: 1.0
bias:
  desc: null
  value: false
bottleneck:
  desc: null
  value: true
data_dir:
  desc: null
  value: /mnt/16THDD/Fred/FredH/CILAB/data
dataset:
  desc: null
  value: imagenet
datatag:
  desc: null
  value: imagenet100
decode_type:
  desc: null
  value: bound
depth:
  desc: null
  value: 10
distributed_num:
  desc: null
  value: null
dsa:
  desc: null
  value: false
dsa_strategy:
  desc: null
  value: color_crop_flip_scale_rotate
dseed:
  desc: null
  value: 0
early:
  desc: null
  value: 0
epoch_print_freq:
  desc: null
  value: 6
epochs:
  desc: null
  value: 600
f_idx:
  desc: null
  value: '4'
factor:
  desc: null
  value: 3
fc:
  desc: null
  value: false
fix_iter:
  desc: null
  value: -1
imagenet_dir:
  desc: null
  value: ../mnt/16THDD/Fred/FredH/CILAB/data/imagenet/
init:
  desc: null
  value: mix
inner_loop:
  desc: null
  value: 100
ipc:
  desc: null
  value: 20
load_memory:
  desc: null
  value: false
lr:
  desc: null
  value: 0.1
lr_img:
  desc: null
  value: 0.002
match:
  desc: null
  value: grad
metric:
  desc: null
  value: l1
mix_p:
  desc: null
  value: 1.0
mixup:
  desc: null
  value: cut
mixup_net:
  desc: null
  value: cut
modeltag:
  desc: null
  value: resnet10apin
mom_img:
  desc: null
  value: 0.5
momentum:
  desc: null
  value: 0.9
n_data:
  desc: null
  value: 500
name:
  desc: null
  value: ''
nch:
  desc: null
  value: 3
nclass:
  desc: null
  value: 100
nclass_sub:
  desc: null
  value: 10
net_epoch:
  desc: null
  value: 1
net_type:
  desc: null
  value: resnet_ap
niter:
  desc: null
  value: 500
norm_type:
  desc: null
  value: instance
phase:
  desc: null
  value: 0
pool_number:
  desc: null
  value: 10
pretrained:
  desc: null
  value: false
pretrained_dir:
  desc: null
  value: ./pretrained/imagenet100/resnet10apin_cut_dsa_p
print_freq:
  desc: null
  value: 10
pruning_ratio:
  desc: null
  value: 0.95
pruning_type:
  desc: null
  value: global
pt_from:
  desc: null
  value: -1
pt_num:
  desc: null
  value: 1
repeat:
  desc: null
  value: 1
reproduce:
  desc: null
  value: false
rrc:
  desc: null
  value: true
same_compute:
  desc: null
  value: false
sample_accrange:
  desc: null
  value:
  - 60
  - 70
save_ckpt:
  desc: null
  value: false
save_dir:
  desc: null
  value: './results/imagenet100/resnet10apin_grad_l1_nd500_cut_nlr0.1_wd0.0001_factor3_bound_lr0.002_mom_img0.5_b_real128_mix_ipc:20_sample_accrange:(60-70)_poolNumber:
    10_pretrained:resnet10apin_cut_dsa_p_10_phase0'
seed:
  desc: null
  value: 0
size:
  desc: null
  value: 224
slct_type:
  desc: null
  value: idc
tag:
  desc: null
  value: '_grad_l1_nd500_cut_nlr0.1_wd0.0001_factor3_bound_lr0.002_mom_img0.5_b_real128_mix_ipc:20_sample_accrange:(60-70)_poolNumber:
    10_pretrained:resnet10apin_cut_dsa_p_10_phase0'
test:
  desc: null
  value: false
time:
  desc: null
  value: false
track_training:
  desc: null
  value: false
verbose:
  desc: null
  value: false
weight_decay:
  desc: null
  value: 0.0001
width:
  desc: null
  value: 1.0
workers:
  desc: null
  value: 8
